#simple playbook to patch rhel servers

- name: patch update
  hosts: db_servers
  become: true
  tasks:
    - name: initaite patching
      ansible.builtin.dnf:
        name: kernel
        state: latest

    - name: initiate reboot
      ansible.builtin.reboot:
        msg: " server will be rebooting soon"
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
