- name: setup redis
  hosts: redis
  become: true
  tasks:
    - name: disable redis
      ansible.builtin.command: dnf module disable redis -y
    - name: enable redis
      ansible.builtin.command: dnf module enable redis:7 -y
    - name: installing redis
      ansible.builtin.package:
         name: redis
         state: present

    - name: update listen address
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Update protected-mode from yes to no in /etc/redis/redis.conf
      ansible.builtin.lineinfile:
         path: /etc/redis/redis.conf
         regexp: 'protected-mode'
         line: 'protected-mode no'
    
    - name: Start & Enable Redis Service
      ansible.builtin.service:
        name: redis
        enabled: true
        state: started


