- name: play level variables
  hosts: local
  connection: local
  vars:
    USERID: anilk
    PASSWDORD: anilk@1234
  tasks:
    - name: print with variable
      vars:
       USERID: Kavyakathoju
      ansible.builtin.debug:
       msg: "Username is : {{ USERID }}, Passw0rd is: {{ PASSWDORD }}" 