- name: package installation
  hosts: local
  connection: local
  become: true
  tasks:
   - name: install packages
     ansible.builtin.package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
     loop:
     - { name: "nginx", state: "present" }
     - { name: "mysql", state: "present" }
     - { name: "zip", state: "present" }
   